import type {
  ProjectData,
  WorkExperience,
  HobbyData,
  ExternalLink,
  AboutData,
} from './types/data';

export const independentProjectsData: ProjectData[] = [
  {
    title: 'Live Design System',
    year: 2024,
    activelyMaintained: true,
    body: 'A parametric Classic Windows bevel design system you can edit live in the browser - adjust colors, shadows, spacing, motion, and radii and watch the whole component library update instantly.',
    live: '/design-system',
    href: 'https://github.com/ianrios/ianrios.github.io/tree/main/src/pages/admin',
    tools: ['React', 'SCSS', 'CSS Custom Properties', 'JavaScript'],
  },
  {
    title: 'Marching Cubes',
    year: 2021,
    activelyMaintained: false,
    info: 'https://en.wikipedia.org/wiki/Marching_cubes',
    img_src_arr: ['./img/metaspheres.png'],
    body: 'A real-time metaball field rendered with the marching cubes algorithm. Built to show my passion for math, design, and interactive 3D on the web.',
    href: 'https://github.com/ianrios/ianrios.github.io/tree/main/src/three',
    live: '/metaballs',
    tools: [
      'Three.js',
      'React',
      'JavaScript',
      'React-Three-Paper',
      'React Three Fiber',
    ],
  },
  {
    title: 'The Algorithm Knows Best',
    year: 2021,
    activelyMaintained: false,
    img_src_arr: ['./img/takb.png'],
    body: 'A reverse-entropy based algorithm for optimizing song order for playlists. Built within a self-contained streaming platform on a single album of music meant to be played on shuffle. Showcased as an interactive installation at the Studio 300 Music and Art Conference.',
    href: 'https://github.com/ianrios/the-algo-knows-best',
    live: 'https://the-algorithm-knows-best.web.app',
    tools: [
      'React',
      'JavaScript',
      'Bootstrap',
      'Laravel',
      'PHP',
      'Firebase',
      'React Router',
      'Google Cloud',
    ],
  },
  {
    title: 'Cortex',
    year: 2026,
    activelyMaintained: true,
    body: 'Agent-steering system for AI coding workflows: shared context files, planning conventions, and review lifecycle used across this portfolio, Petal, and WRC.',
    href: '',
    live: '',
    tools: [],
  },
  {
    title: 'Petal',
    year: 2026,
    activelyMaintained: true,
    body: 'Details coming soon.',
    href: '',
    live: '',
    tools: [],
  },
  {
    title: 'neThing',
    year: 2018,
    activelyMaintained: false,
    tools: ['Node.js', 'Bootstrap', 'Pure Data'],
    img_src_arr: ['./img/interface_JS_42218.png'],
    body: 'An Educational Open-Source Web-based Graphical User Interface for Controlling Ambisonic and Wave Field Speaker Arrays.',
    href: 'https://github.com/ianrios/neThing',
    live: '',
  },
  {
    title: 'Grandulator',
    year: 2017,
    activelyMaintained: false,
    tools: ['Max MSP'],
    img_src_arr: ['./img/grandulator.png', './img/controls.png'],
    body: 'Ensemble performance instrument that allows for real time autotuning of live granular synthesis.',
    href: 'https://github.com/ianrios/Grandulator',
    live: '',
  },
  {
    title: 'RAAPT V1',
    year: 2017,
    activelyMaintained: false,
    tools: ['Max MSP'],
    img_src_arr: ['./img/V1.png'],
    body: 'The RAAPT project generates rhythmic musical structures by assigning pre-made templates to ecological soundscapes. By applying structural templates to audio clips, RAAPT creates an automated and generative music system capable of transforming any sonic material into rhythmic, musical instruments.',
    href: 'https://github.com/ianrios/RAAPT',
    live: '',
  },
];

export const workProjectsData: WorkExperience[] = [
  {
    company: 'Atrix',
    title: 'Senior Software Engineer',
    phase: 'Senior Software Engineer',
    startYear: 2026,
    endYear: null,
    bullets: [],
  },
  {
    company: 'Built Technologies',
    title: 'Software Engineer II',
    phase: 'Software Engineer II',
    startYear: 2024,
    endYear: 2026,
    bullets: [
      'Built internal AI-assisted engineering workflows and best practices adopted across 60+ engineers, contributing to a measured 20 to 25% increase in engineering delivery velocity.',
      'Architected and deployed an LLM-guided support triage agent processing about 10,000 alerts weekly, reducing alert noise from about 90% to 50% over 6 months and saving on-call engineers about 6 hours daily.',
      'Consolidated fragmented UX surfaces into reusable component systems across 5 major initiatives, unblocking 10+ product features previously constrained by duplicated implementations.',
      'Led architectural decisions and standards-setting for the Frontend Guild, a 3-person team managing the React design system and shared component libraries used by 12+ engineering teams.',
      'Expanded Playwright infrastructure from isolated end-to-end tests into persona-aware testing flows spanning 100+ feature flags, 6 personas, and 4 environments.',
    ],
    companyUrl: 'https://getbuilt.com/',
  },
  {
    company: 'Big Ass Fans',
    title: 'Software Engineer II',
    phase: 'Software Engineer II',
    startYear: 2022,
    endYear: 2023,
    bullets: [
      'Architected and built the Sales Toolbox MVP, a platform of 11 integrated web apps for sales engineers, reducing quote generation time from days to hours.',
      'Architected Funnel, a project timeline management tool providing real time visibility across 20 to 30 concurrent company projects.',
      'Led a 2-person team improving SpecLab, a legacy 3D CFD simulation tool, reducing production defects by 35% and expanding product capabilities.',
      'Developed the AR Virtual Showroom, a React-based product visualization platform that won two Lexington American Advertising Awards and increased customer conversion by 15%.',
      'Led a 3-person team building BAFConX, an automated climate-control system for industrial-scale deployment with LoRa WAN sensor networks.',
      'Modernized engineering infrastructure across all products with Terraform, Docker, GitHub Actions, and shared VS Code configurations.',
      'Mentored software engineering interns through project ownership, onboarding, and engineering best practices.',
    ],
    companyUrl: 'https://bigassfans.com/',
  },
  {
    company: 'Luxury Garage Sale',
    title: 'Full Stack Web Developer (Contract)',
    phase: 'Early Career',
    startYear: 2020,
    endYear: 2020,
    bullets: [
      'Built React, Redux, and Ant Design workflows integrating with Salesforce APIs, automating product intake operations.',
    ],
    companyUrl: 'https://www.instagram.com/luxurygaragesale/',
  },
  {
    company: 'Apax Software',
    title: 'Full Stack Web Developer (Contract)',
    phase: 'Early Career',
    startYear: 2019,
    endYear: 2019,
    bullets: [
      'Built and tested full stack applications using React and Next.js frontends with Django APIs across multiple client projects.',
    ],
    companyUrl: 'https://www.apaxsoftware.com/',
  },
  {
    company: 'Awesome Inc',
    title: 'Bootcamp Instructor',
    phase: 'Early Career',
    startYear: 2019,
    endYear: 2021,
    bullets: [
      'Taught full stack web development and agile concepts to 60+ students with a 90% job placement rate within 6 months of graduation.',
      'Developed 35 video tutorials covering React fundamentals through advanced full stack patterns.',
      'Led simulated engineering team exercises focused on collaborative development workflows and agile practices.',
    ],
    companyUrl: 'https://awesomeinc.org/',
  },
  {
    company: 'Conversant Media',
    title: 'System Engineer & Administrator',
    phase: 'Early Career',
    startYear: 2018,
    endYear: 2019,
    bullets: [
      'Developed multithreaded Python automation tooling supporting global BIOS configuration updates and incident response workflows across 950+ production servers.',
    ],
    companyUrl: 'https://www.epsilon.com/us',
  },
  {
    company: 'My Music Machines',
    title: 'Software Development Consultant',
    phase: 'Early Career',
    startYear: 2017,
    endYear: 2017,
    bullets: [
      'Designed assistive music software and educational tooling for disabled musicians using tactile and visual UI systems, building the Jamboxx product.',
      'Built Score Reader, a Jamboxx Max for Live patch that highlights the current note to play based on song location and MIDI transport position.',
      'Built Falling Notes, a Jamboxx Max for Live patch that visualizes upcoming notes in time with a metronome.',
    ],
    companyUrl: 'https://sites.google.com/view/jamboxx/home',
  },
  {
    company: 'Center for Cognition, Communication & Culture, RPI',
    title: 'Researcher',
    phase: 'Research',
    startYear: 2017,
    endYear: 2017,
    bullets: [
      'Led undergraduate research initiatives focused on assistive music technologies and audiovisual networking systems.',
      'Presented research at the International Symposium on Adaptive Technology in Music and Art (ISATMA).',
      'Built MIDI Receive UDP, a Max for Live patch allowing users to sync MIDI transports over a network connection via Ableton Link.',
      'Built MIDI Send UDP, a Max for Live patch allowing users to sync MIDI transports over a network connection via Ableton Link.',
    ],
    companyUrl:
      'https://catalog.rpi.edu/content.php?catoid=15&navoid=355#Center%20for%20Cognition,%20Communication,%20and%20Culture',
  },
];

export const hobbyData: HobbyData[] = [
  {
    title: "We're Eating Good Tonight",
    year: 2021,
    activelyMaintained: false,
    img_src_arr: ['./img/wegt2.png'],
    body: "I was able to turn one of my favorite hobbies that I get to do every day - cooking delicious food and giving others joy in tasting it, into a profitable business. I worked as a personal chef meal prepping lunches for my co-workers. Learning business management skills, budgeting, and food safety was a challenge while balancing my full time software career and trying to make local industry connections, but I still was able to deliver inexpensive, high-quality, nourishing food for my clients. When I'm not doing that, I am constantly experimenting in the kitchen for at-home meals.",
    url: '',
    instagram: 'https://www.instagram.com/wereeatinggoodtonight/',
  },
  {
    title: 'WRC Label Manager',
    year: 2019,
    activelyMaintained: true,
    img_src_arr: ['./img/wrc_site.png'],
    body: "My most complex hobby - an independently owned and operated record label, featuring some of my favorite artists and friends from around the globe. I've utilized a majority of my software background to help the label achieve success by creating automation tools for logistics and social media.",
    url: 'https://whyrecord.com',
    instagram: 'https://www.instagram.com/whyrecordcompany/',
  },
  {
    title: 'Music Production',
    year: 2015,
    activelyMaintained: true,
    img_src_arr: ['./img/profile.JPG'],
    body: 'If you\'ve gotten this far, you already know that I love creating pretty much everything. "whythough?" and "Wash And Fold Laundry Service" are just a few of the many artist personas I have developed based on a focused genre or sound. Although this persona is focused on experimental electronic music, I enjoy producing most genres of electronic music, as well as DJing all sorts of music.',
    url: 'https://whyrecord.com/artist/wash-and-fold-laundry-service/',
    instagram: 'https://www.instagram.com/whythough000',
  },
  {
    title: 'KY FIRST Robotics',
    year: 2025,
    activelyMaintained: false,
    img_src_arr: [],
    body: 'Led standups and managed project delivery for software interns participating in the KY FIRST Robotics summer program, mentoring students on agile and software engineering fundamentals, communication, and team collaboration practices.',
    url: 'https://www.kyfirstrobotics.org/',
    instagram: '',
    kind: 'volunteering',
  },
  {
    title: 'Open Source Breakfast Club',
    year: 2019,
    activelyMaintained: false,
    img_src_arr: [],
    body: 'Organized weekly workshops covering open-source software and emerging technologies led by rotating technical guests, as lead facilitator.',
    url: '',
    instagram: '',
    kind: 'volunteering',
  },
];

export const aboutData: AboutData = {
  bio: "I'm a software engineer with 8 years of experience building web platforms, AI-assisted engineering workflows, and developer productivity systems. My work spans component architecture, full-stack SaaS infrastructure, frontend design systems, testing reliability, and operational AI systems. I like designing systems from the ground up, setting architectural standards that hold up years later, and building tooling that measurably improves how fast and how well a team can ship.",
  personal:
    "Outside of work I run WRC, an independently owned record label I built the artist portal and store for, and I produce and DJ electronic music under a rotating cast of aliases. I've also worked as a personal chef, cooking and delivering meals for coworkers as a small side business, because I like feeding people almost as much as I like building things for them. I studied Electronic Arts and Computer Music alongside computer science at RPI, and that mix of engineering and craft still shows up in how I approach this site. I mentor engineers when I can, whether that's leading standups for the KY FIRST Robotics summer program or running workshops through the Open Source Breakfast Club.",
  closing:
    'This site is built the way I build everything now: by directing AI coding agents. The engineering is in the orchestration. Getting the most from an agent on the fewest tokens, keeping context sharp before it degrades, and building the tooling and workflows that make that repeatable is the actual work. Setting the direction and owning the system is the job.',
};

export const externalLinks: ExternalLink[] = [
  { label: 'personal github', href: 'https://github.com/ianrios/' },
  { label: 'built github', href: 'https://github.com/ianriosbuilt' },
  { label: 'baf github', href: 'https://github.com/ianriosbaf' },
  { label: 'linkedin', href: 'https://www.linkedin.com/in/ian-rios/' },
  { label: 'instagram', href: 'https://www.instagram.com/ian___rios' },
];
